# Generated by Django 5.0.7 on 2024-08-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_recursos_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='texto',
            field=models.CharField(max_length=100, verbose_name='Texto'),
        ),
    ]
