# Generated by Django 5.0.7 on 2024-08-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_recurso_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='texto',
            field=models.TextField(max_length=200, verbose_name='Texto'),
        ),
    ]
